spring.config.import: "configserver:"
spring:
  application:
    name: order-service
  profiles:
    active: development
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8081/
    username: admin
    password: admin123


